export const teamStatsSeed: Record<string, { stars: string[]; sourceName: string }> = {
  MEX: { stars: ['Santiago Gimenez', 'Edson Alvarez', 'Hirving Lozano'], sourceName: 'Curado inicial' },
  RSA: { stars: ['Ronwen Williams', 'Teboho Mokoena', 'Percy Tau'], sourceName: 'Curado inicial' },
  KOR: { stars: ['Son Heung-min', 'Kim Min-jae', 'Lee Kang-in'], sourceName: 'Curado inicial' },
  CZE: { stars: ['Patrik Schick', 'Tomas Soucek', 'Adam Hlozek'], sourceName: 'Curado inicial' },
  CAN: { stars: ['Alphonso Davies', 'Jonathan David', 'Tajon Buchanan'], sourceName: 'Curado inicial' },
  BIH: { stars: ['Edin Dzeko', 'Miralem Pjanic', 'Ermedin Demirovic'], sourceName: 'Curado inicial' },
  QAT: { stars: ['Akram Afif', 'Almoez Ali', 'Hassan Al-Haydos'], sourceName: 'Curado inicial' },
  SUI: { stars: ['Granit Xhaka', 'Manuel Akanji', 'Breel Embolo'], sourceName: 'Curado inicial' },
  BRA: { stars: ['Vinicius Junior', 'Rodrygo', 'Alisson'], sourceName: 'Curado inicial' },
  MAR: { stars: ['Achraf Hakimi', 'Hakim Ziyech', 'Yassine Bounou'], sourceName: 'Curado inicial' },
  HAI: { stars: ['Duckens Nazon', 'Frantzdy Pierrot', 'Jean-Ricner Bellegarde'], sourceName: 'Curado inicial' },
  SCO: { stars: ['Scott McTominay', 'Andy Robertson', 'John McGinn'], sourceName: 'Curado inicial' },
  USA: { stars: ['Christian Pulisic', 'Weston McKennie', 'Tyler Adams'], sourceName: 'Curado inicial' },
  AUS: { stars: ['Mathew Ryan', 'Harry Souttar', 'Jackson Irvine'], sourceName: 'Curado inicial' },
  PAR: { stars: ['Miguel Almiron', 'Julio Enciso', 'Gustavo Gomez'], sourceName: 'Curado inicial' },
  TUR: { stars: ['Hakan Calhanoglu', 'Arda Guler', 'Kenan Yildiz'], sourceName: 'Curado inicial' },
  GER: { stars: ['Jamal Musiala', 'Florian Wirtz', 'Joshua Kimmich'], sourceName: 'Curado inicial' },
  ECU: { stars: ['Moises Caicedo', 'Piero Hincapie', 'Enner Valencia'], sourceName: 'Curado inicial' },
  CIV: { stars: ['Sebastien Haller', 'Franck Kessie', 'Simon Adingra'], sourceName: 'Curado inicial' },
  CUW: { stars: ['Leandro Bacuna', 'Juninho Bacuna', 'Vurnon Anita'], sourceName: 'Curado inicial' },
  NED: { stars: ['Virgil van Dijk', 'Frenkie de Jong', 'Cody Gakpo'], sourceName: 'Curado inicial' },
  JPN: { stars: ['Kaoru Mitoma', 'Takefusa Kubo', 'Wataru Endo'], sourceName: 'Curado inicial' },
  TUN: { stars: ['Ellyes Skhiri', 'Hannibal Mejbri', 'Youssef Msakni'], sourceName: 'Curado inicial' },
  SWE: { stars: ['Alexander Isak', 'Dejan Kulusevski', 'Viktor Gyokeres'], sourceName: 'Curado inicial' },
  BEL: { stars: ['Kevin De Bruyne', 'Romelu Lukaku', 'Jeremy Doku'], sourceName: 'Curado inicial' },
  IRN: { stars: ['Mehdi Taremi', 'Sardar Azmoun', 'Alireza Jahanbakhsh'], sourceName: 'Curado inicial' },
  EGY: { stars: ['Mohamed Salah', 'Omar Marmoush', 'Trezeguet'], sourceName: 'Curado inicial' },
  NZL: { stars: ['Chris Wood', 'Liberato Cacace', 'Marko Stamenic'], sourceName: 'Curado inicial' },
  ESP: { stars: ['Lamine Yamal', 'Rodri', 'Pedri'], sourceName: 'Curado inicial' },
  URU: { stars: ['Federico Valverde', 'Darwin Nunez', 'Ronald Araujo'], sourceName: 'Curado inicial' },
  KSA: { stars: ['Salem Al-Dawsari', 'Firas Al-Buraikan', 'Mohammed Kanno'], sourceName: 'Curado inicial' },
  CPV: { stars: ['Ryan Mendes', 'Garry Rodrigues', 'Logan Costa'], sourceName: 'Curado inicial' },
  FRA: { stars: ['Kylian Mbappe', 'Ousmane Dembele', 'Aurelien Tchouameni'], sourceName: 'Curado inicial' },
  SEN: { stars: ['Sadio Mane', 'Kalidou Koulibaly', 'Nicolas Jackson'], sourceName: 'Curado inicial' },
  NOR: { stars: ['Erling Haaland', 'Martin Odegaard', 'Alexander Sorloth'], sourceName: 'Curado inicial' },
  IRQ: { stars: ['Aymen Hussein', 'Ali Jasim', 'Zidane Iqbal'], sourceName: 'Curado inicial' },
  ARG: { stars: ['Lionel Messi', 'Julian Alvarez', 'Lautaro Martinez'], sourceName: 'Curado inicial' },
  AUT: { stars: ['David Alaba', 'Marcel Sabitzer', 'Konrad Laimer'], sourceName: 'Curado inicial' },
  ALG: { stars: ['Riyad Mahrez', 'Ismael Bennacer', 'Amine Gouiri'], sourceName: 'Curado inicial' },
  JOR: { stars: ['Mousa Al-Taamari', 'Yazan Al-Naimat', 'Nizar Al-Rashdan'], sourceName: 'Curado inicial' },
  POR: { stars: ['Cristiano Ronaldo', 'Bruno Fernandes', 'Bernardo Silva'], sourceName: 'Curado inicial' },
  COL: { stars: ['Luis Diaz', 'James Rodriguez', 'Jhon Duran'], sourceName: 'Curado inicial' },
  UZB: { stars: ['Eldor Shomurodov', 'Abdukodir Khusanov', 'Jaloliddin Masharipov'], sourceName: 'Curado inicial' },
  COD: { stars: ['Yoane Wissa', 'Cedric Bakambu', 'Chancel Mbemba'], sourceName: 'Curado inicial' },
  ENG: { stars: ['Harry Kane', 'Jude Bellingham', 'Bukayo Saka'], sourceName: 'Curado inicial' },
  CRO: { stars: ['Luka Modric', 'Josko Gvardiol', 'Mateo Kovacic'], sourceName: 'Curado inicial' },
  PAN: { stars: ['Adalberto Carrasquilla', 'Michael Murillo', 'Jose Fajardo'], sourceName: 'Curado inicial' },
  GHA: { stars: ['Mohammed Kudus', 'Thomas Partey', 'Jordan Ayew'], sourceName: 'Curado inicial' }
};
